Allow null canned acl
ohnosequences/ivy-s3-resolver pull request #20
Opened 2017-09-25 21:20 UTC by hkupty

So, in this case, no acl will be set to the object,
causing it to inherit the bucket rules.

This won't break anything, but allow ohnosequences/sbt-s3-resolver#54 to be solved.

2017-09-25 21:58 UTC, laughedelic requested changes
This is a good idea and the implementation is really simple 👌 

I think this library isn't used anywhere except the sbt plugin 😅  So I'm more concerned about keeping the interface nice (see the comment below) and not afraid of breaking things here (also it's still not v1.x).

Also, _if_ you could write a simple test for this case, it would be much appreciated. Smth like having a mock-bucket with a preset ACL and then putting an object (without ACL parameter) and checking that the resulting ACL is the one of the bucket.

2017-09-25 21:58 UTC, laughedelic commented on src/main/java/ohnosequences/ivy/S3Repository.java
> +    }
This check looks good on its own, but I don't like the idea of passing `null` when you want to leave ACL unset. 

How about changing its type in the [`S3Repository` constructor](https://github.com/nubank/ivy-s3-resolver/blob/c191a4bfcbd96dd4a8d3b12f8588c557ea15867e/src/main/java/ohnosequences/ivy/S3Repository.java#L109) to `Optional<CannedAccessControlList>` and adjusting the other constructors accordingly?

2017-09-25 21:58 UTC, laughedelic commented on notes/0.12.1.markdown
> +* Allowed `CannedAccessControlList` to be null, in which case no specific ACL is set for the object;
Thanks for keeping changelog 👍 
Rename the file to `changelog.md`, please. Then the release pipeline will pick it up and rename to the corresponding version. I think it will be `0.13.0` rather than `0.12.1`, because it's not a bug fix, but a feature 😆

2017-09-25 22:03 UTC, michaelahlers commented on src/main/java/ohnosequences/ivy/S3Repository.java
> +    }
I second that. I'd even encourage making that change comprehensively wherever applicable.

2017-09-25 22:05 UTC, hkupty commented on src/main/java/ohnosequences/ivy/S3Repository.java
> +    }
While I totally agree with that, I avoided breaking the contract with what is currently stablished.
This seemed the minimum effort to make it happen.

Nonetheless, makes sense. I'll fix this.

2017-09-25 22:05 UTC, hkupty commented on notes/0.12.1.markdown
> +* Allowed `CannedAccessControlList` to be null, in which case no specific ACL is set for the object;
Great, makes sense. I'll change that as well.

2017-09-25 22:27 UTC, hkupty commented
> Also, if you could write a simple test for this case, it would be much appreciated. Smth like having a mock-bucket with a preset ACL and then putting an object (without ACL parameter) and checking that the resulting ACL is the one of the bucket.

Most of the requested changes are in place, except for the test. I'm not really sure we can test the result ACL is the one of the bucket since, AFAIK, this happens on server side, when you send a request with no ACL attached.

2017-09-25 22:42 UTC, laughedelic requested changes
One little thing. Other than that looks good 👍

2017-09-25 22:42 UTC, laughedelic commented on src/main/java/ohnosequences/ivy/S3Repository.java
> +      Optional.of(acl),
Just in case, change this to `.ofNullable`

2017-09-25 22:44 UTC, laughedelic commented
> I'm not really sure we can test the result ACL is the one of the bucket since, AFAIK, this happens on server side, when you send a request with no ACL attached.

Makes sense. I forgot that `PutObjectRequest` just takes a bucket name and doesn't know anything about its permissions.

2017-09-25 23:12 UTC, hkupty commented on src/main/java/ohnosequences/ivy/S3Repository.java
> +      Optional.of(acl),
Sure! Will fix

2017-09-26 04:42 UTC, hkupty commented
I did some checks locally and the S3Resolver was missing. Changed there as well.
I'm hoping that this can be merged soon, but I totally understand if anything else needs changing.

Thanks for accepting the issue and both PRs.
Cheers,
Henry Kupty.

2017-09-26 09:49 UTC, laughedelic approved these changes

2017-09-26 09:53 UTC, laughedelic commented
Great! Thanks @hkupty!

2017-09-26 09:53 UTC, merged

2017-09-26 10:11 UTC, laughedelic commented
Released: https://github.com/ohnosequences/ivy-s3-resolver/releases/tag/v0.13.0